### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by bardiharborow** [Syriven/netvend-proto#6]
http://www.reddit.com/r/Bitcoin/comments/26l3l1/10_months_ago_i_posted_the_idea_for_coinflow_a/chs94ia

**Comment by bardiharborow** [comment]
Ooops, just read lower and realised it is the VARCHAR(5000) limit.

**Comment by kkirss** [comment]
Oh yeah that makes sense :D

But the TEXT limitation of 65535 bytes still exists.

**Comment by bardiharborow** [comment]
@runekri3 I'll have to use LONGTEXT then. =)

**Comment by kkirss** [comment]
Yeah but did you read http://www.reddit.com/r/Bitcoin/comments/26l3l1/10_months_ago_i_posted_the_idea_for_coinflow_a/chsfr9i ? Seems that other data types might need to be changed aswell.

Please let me know when any of those changes will be made :)
